name: Jekyll site CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Checkout Repository

    - name: Adding Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20.19.0

    - name: Install Dependencies
      run: npm install

    - name: Build Angular App
      run: npm run build        

    - name: Deploy to gh pages
      run: |
        npx angular-cli-ghpages --dir=dist/your-angular-app
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}      
